---
- name: Converge
  hosts: all
  vars:
    galaxy_mutable_data_dir: /opt/galaxy/data
    galaxy_config_dir: /opt/galaxy/data
    galaxy_server_dir: /opt/galaxy/server
    galaxy_extensions_enabled:
      - tips
      - search
      - tool_list
    galaxy_version: "24.1"

  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'

  tasks:
    - name: Include extensions-ansible-role role
      include_role:
        name: extensions-ansible-role

  handlers:
    - name: restart galaxy
      debug:
        msg: "Galaxy would be restarted here"
